get:
  x-eov-operation-id: getExecutions
  x-eov-operation-handler: v1/handlers/executions/executions.handler
  tags:
    - Execution
  summary: Retrieve all executions
  description: Retrieve all executions from your instance.
  parameters:
    - $ref: '../schemas/parameters/includeData.yml'
    - name: status
      in: query
      description: Status to filter the executions by.
      required: false
      schema:
        oneOf:
          - type: string
            enum: ['canceled', 'crashed', 'error', 'failed', 'new', 'running', 'success', 'unknown', 'waiting']
          - type: array
            minItems: 1
            items:
              type: string
              enum: ['canceled', 'crashed', 'error', 'failed', 'new', 'running', 'success', 'unknown', 'waiting']
    - name: workflowId
      in: query
      description: Workflow to filter the executions by.
      required: false
      schema:
        type: string
        example: '1000'
    - $ref: '../../../../shared/spec/parameters/limit.yml'
    - $ref: '../../../../shared/spec/parameters/cursor.yml'
  responses:
    '200':
      description: Operation successful.
      content:
        application/json:
          schema:
            $ref: '../schemas/executionList.yml'
    '401':
      $ref: '../../../../shared/spec/responses/unauthorized.yml'
    '404':
      $ref: '../../../../shared/spec/responses/notFound.yml'
